document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.post-date').forEach(function(el){const date=new Date(el.dataset.date);const formatted=date.toLocaleDateString('sl-SI',{weekday:'long',day:'numeric',month:'long',year:'numeric'});el.textContent=formatted;});});document.addEventListener("DOMContentLoaded",function(){const elements=[...document.querySelectorAll('td.tr-caption'),...document.querySelectorAll('.separator')];const PhotosRange=localStorage.getItem('photosSliderValue')||initPhotos;function isWithinRange(dataSkip){if(dataSkip==="NA"||dataSkip===null||dataSkip===undefined){dataSkip="3";}
dataSkip=dataSkip.replace(/best/g,"0").replace(/cover/g,"-1").replace(/peak/g,"5");const dataSkipValues=dataSkip.split(";");const numericValues=dataSkipValues.map(value=>parseFloat(value)).filter(value=>!isNaN(value));const minValue=Math.min(...numericValues);return minValue>PhotosRange?1:0;}
elements.forEach(element=>{const isCaption=element.classList.contains('tr-caption');const isSeparator=element.classList.contains('separator');if(isCaption){const title=element.textContent.trim();const link=element.closest('tr').previousElementSibling?.querySelector('a[href*="blogger.googleusercontent.com"]');if(link){link.setAttribute('data-title',title);}
const img=element.closest('tr').previousElementSibling?.querySelector('a img');if(img&&isWithinRange(img.getAttribute('data-skip'))){const table=element.closest('table');if(table)table.remove();}}else if(isSeparator){const img=element.querySelector('img');const text=element.textContent.trim();if(img&&isWithinRange(img.getAttribute('data-skip'))){element.remove();}else if(!img&&!text){element.remove();}}});});document.addEventListener("DOMContentLoaded",function(){const showMoreBtn=document.querySelector(".show-more");const showLessBtn=document.querySelector(".show-less");const remainingItems=document.querySelector(".remaining-items");const saved=localStorage.getItem('labelsExpanded');const expanded=saved==='true';if(showMoreBtn&&showLessBtn&&remainingItems){if(expanded){remainingItems.classList.remove('hidden');showMoreBtn.classList.add('hidden');showLessBtn.classList.remove('hidden');}else{remainingItems.classList.add('hidden');showMoreBtn.classList.remove('hidden');showLessBtn.classList.add('hidden');}
showMoreBtn.addEventListener("click",function(){remainingItems.classList.remove("hidden");showMoreBtn.classList.add("hidden");showLessBtn.classList.remove("hidden");localStorage.setItem('labelsExpanded','true');});showLessBtn.addEventListener("click",function(){remainingItems.classList.add("hidden");showMoreBtn.classList.remove("hidden");showLessBtn.classList.add("hidden");localStorage.setItem('labelsExpanded','false');});}});let posts=[];Promise.all([fetch(`${WindowBaseUrl}/data/all-posts.json`).then(r=>r.json()),typeof isRelive!=='undefined'?fetch(`${WindowBaseUrl}/data/all-relive-posts.json`).then(r=>r.json()):Promise.resolve({feed:{entry:[]}})]).then(([normalData,reliveData])=>{const normalEntries=normalData.feed?.entry||[];const reliveEntries=reliveData.feed?.entry||[];const entries=[...normalEntries,...reliveEntries];posts=entries.map((entry,i)=>{const title=entry.title?.$t||`untitled-${i}`;const content=entry.content?.$t||"";const rawLink=entry.link.find(l=>l.rel==="alternate"&&l.type==="text/html")?.href||"#";const link=rawLink.replace(/\/index\.html$/,'/');const thumbnail=entry.media$thumbnail?.url||"";return{title,content,link,thumbnail};});}).catch(error=>{console.error("Error loading feeds:",error);});document.addEventListener("DOMContentLoaded",function(){const searchToggle=document.getElementById("searchToggle");const searchContainer=document.getElementById("searchContainer");const searchClose=document.getElementById("searchClose");const searchBox=document.getElementById("searchBox");const resultsContainer=document.getElementById("searchResults");searchToggle.addEventListener("click",()=>{const isVisible=searchContainer.classList.toggle("visible");if(!isVisible){closeSearchOverlay();}else{searchBox.focus();}});(function(){const detailSelector='details.month-group, details.year-group';const allDetails=Array.from(document.querySelectorAll(detailSelector));if(allDetails.length===0)return;allDetails.forEach(d=>{d.addEventListener('toggle',()=>{if(d.open){allDetails.forEach(other=>{if(other!==d)other.open=false;});}});});allDetails.forEach(d=>{d.querySelectorAll&&d.querySelectorAll('a').forEach(a=>{a.addEventListener('click',function(e){const parent=a.closest('details');if(!parent)return;allDetails.forEach(other=>{if(other!==parent)other.open=false;});parent.open=true;const monthDescendants=parent.querySelectorAll('details.month-group');if(monthDescendants&&monthDescendants.length>0){const lastMonth=monthDescendants[monthDescendants.length-1];allDetails.forEach(other=>{if(other.matches&&other.matches('details.month-group')&&other!==lastMonth)other.open=false;});lastMonth.open=true;}});});});})();searchClose.addEventListener("click",()=>{closeSearchOverlay();});searchBox.addEventListener("input",function(){const keyword=this.value.toLowerCase();resultsContainer.innerHTML="";if(!keyword){resultsContainer.classList.add("overlay-hidden");resultsContainer.classList.remove("overlay-visible");return;}
const filtered=posts.filter(post=>post.title.toLowerCase().includes(keyword)||post.content.toLowerCase().includes(keyword));if(filtered.length>0){let resultHTML=`
        <button class="close-button" onclick="closeSearchOverlay()">×</button>
        <h1>Prikaz objav, ki vsebujejo: ${keyword}</h1>
        <div class="search-posts-container">`;filtered.forEach(post=>{resultHTML+=`
          <div class="post-container">
            <a href="${post.link}" class="image-link">
              <div class="image-wrapper">
                ${post.thumbnail ? `<img src="${post.thumbnail.replace(/\/s\d+-c/, '/s300')}"alt="Thumbnail for ${post.title}"class="post-thumb">` : ""}
                <h3 class="overlay-title">${post.title}</h3>
              </div>
            </a>
          </div>`;});resultHTML+=`</div>`;resultsContainer.innerHTML=resultHTML;resultsContainer.classList.remove("overlay-hidden");resultsContainer.classList.add("overlay-visible");}else{resultsContainer.classList.add("overlay-hidden");resultsContainer.classList.remove("overlay-visible");}});window.closeSearchOverlay=function(){resultsContainer.innerHTML="";resultsContainer.classList.add("overlay-hidden");resultsContainer.classList.remove("overlay-visible");searchBox.value="";searchContainer.classList.remove("visible");};});function toggleSidebar(){const sidebar=document.getElementById("sidebar");sidebar.classList.toggle("visible");}
document.addEventListener("DOMContentLoaded",function(){const entries=document.querySelectorAll(".photo-entry");const entriesPerPage=12;const totalPages=Math.ceil(entries.length/entriesPerPage);const pager=document.getElementById("blog-pager");let currentPage=1;if(!pager){return;}
function redirectpage(page){if(page<1||page>totalPages)return;currentPage=page;showPage(currentPage);}
function showPage(page){entries.forEach(entry=>{if(parseInt(entry.dataset.page)===page){entry.classList.remove("visually-hidden");}else{entry.classList.add("visually-hidden");}});document.querySelectorAll(`.photo-entry[data-page="${page}"] img[data-src]`).forEach(img=>{img.src=img.dataset.src;img.removeAttribute('data-src');});renderPager(page);window.scrollTo({top:0,behavior:'smooth'});}
function renderPager(page){if(totalPages<=1){pager.style.display="none";return;}else{pager.style.display="flex";}
pager.innerHTML='';pager.innerHTML+=`<span class="displaypageNum">
            <a href="#" onclick="redirectpage(${page - 1}); return false" ${page === 1 ? 'style="pointer-events:none;opacity:0.5;"' : ''}>&laquo;</a>
        </span>`;if(page===1){pager.innerHTML+=`<span class="pagecurrent">1</span>`;}else{pager.innerHTML+=`<span class="displaypageNum"><a href="#" onclick="redirectpage(1); return false">1</a></span>`;}
if(page>3){pager.innerHTML+=`<span class="showpage ellipsis">...</span>`;}
for(let i=page-1;i<=page+1;i++){if(i>1&&i<totalPages){if(i===page){pager.innerHTML+=`<span class="pagecurrent">${i}</span>`;}else{pager.innerHTML+=`<span class="displaypageNum"><a href="#" onclick="redirectpage(${i}); return false">${i}</a></span>`;}}}
if(page<totalPages-2){pager.innerHTML+=`<span class="showpage ellipsis">...</span>`;}
if(page===totalPages){pager.innerHTML+=`<span class="pagecurrent">${totalPages}</span>`;}else{pager.innerHTML+=`<span class="displaypageNum"><a href="#" onclick="redirectpage(${totalPages}); return false">${totalPages}</a></span>`;}
pager.innerHTML+=`<span class="displaypageNum">
            <a href="#" onclick="redirectpage(${page + 1}); return false" ${page === totalPages ? 'style="pointer-events:none;opacity:0.5;"' : ''}>&raquo;</a>
        </span>`;}
window.redirectpage=redirectpage;showPage(currentPage);});const btn=document.getElementById("backToTop");window.addEventListener("scroll",()=>{btn.style.display=window.scrollY>400?"block":"none";});btn.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));async function getRandomPost(){{try{{const[mainRes]=await Promise.all([fetch('https://metodlangus.github.io/data/all-posts.json')]);const mainData=await mainRes.json();const entries=[...(mainData.feed?.entry||[])];if(!entries||entries.length===0){{throw new Error('No posts found');}}
const postLinks=[];for(const entry of entries){{const links=entry.link||[];const postLink=links.find(l=>l.rel==="alternate"&&l.type==="text/html");if(postLink&&postLink.href){{postLinks.push(postLink.href.replace(/\/index\.html$/,'/'));}}}}
if(postLinks.length===0){{throw new Error('No valid post links found');}}
const randomPost=postLinks[Math.floor(Math.random()*postLinks.length)];window.location.href=randomPost;}}catch(error){{console.error('Error fetching posts:',error);window.location.href='https://metodlangus.github.io/';}}}}