const MattiaMapScriptModule=(function(k){let n,p,m={},O={},$={},u=null,c=null,f=null;const B={mapId:"map",sidebarId:"sidebar",toggleBtnId:"toggleSidebar",postListId:"postList",keywordsGeo:k.keywords_geo||{}};function C(s,o,i,d){const y=(i-s)*Math.PI/180,t=(d-o)*Math.PI/180,a=Math.sin(y/2)**2+Math.cos(s*Math.PI/180)*Math.cos(i*Math.PI/180)*Math.sin(t/2)**2;return 12742*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}function S(){!f||!c||f.addEventListener("click",()=>c.classList.toggle("show"))}function z(s){if(!document.getElementById(s.mapId))return console.error(`Map container with ID "${s.mapId}" not found`),!1;n=L.map(s.mapId,{zoomControl:!1}).setView([46.38,13.3],10),L.control.zoom({position:"topright"}).addTo(n);const i=L.tileLayer("https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenTopoMap contributors"}),d=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors"});i.addTo(n),p=L.layerGroup().addTo(n);const M=L.control.layers({OpenTopoMap:i,OpenStreetMap:d},{Adventures:p},{position:"topright"}).addTo(n),t=L.Control.geocoder({position:"topright"}).addTo(n).getContainer();return t.style.marginTop="10px",!0}function E(s){if(!n||!p){console.error("Map not initialized");return}const o=["red","blue","green","orange","purple"];let i=0;const d=[],M=[];for(const[t,a]of Object.entries(s)){const g=o[i%o.length];i++;let r=a.locations.filter(e=>e.lat&&e.lon);if(r.length>1){const e=r.reduce((l,h)=>l+h.lat,0)/r.length,w=r.reduce((l,h)=>l+h.lon,0)/r.length;r=r.filter(l=>C(l.lat,l.lon,e,w)<=100)}const I=[],v=[],T=L.layerGroup(),b=a.date||"",D=b?b.split(" ")[0]:"Date unknown",j=b?new Date(b):new Date(0);if(r.forEach(e=>{const w=L.circleMarker([e.lat,e.lon],{radius:8,color:g,fillColor:g,fillOpacity:.8}).addTo(p).addTo(T),l=`https://mattia-furlan.github.io/mont/escursioni/${t}`;w.bindPopup(`
                    <div class="popup-title">
                        <a href="${l}" target="_blank">${t}</a>
                    </div>
                    <div><strong>${e.name}</strong></div>
                    <div>Date: ${D}</div>
                    <hr>
                    <div>Other places in this post:<br>${r.map(h=>h.name).join(", ")}</div>
                `),v.push(w),I.push([e.lat,e.lon]),d.push([e.lat,e.lon])}),I.length>1){const e=L.polyline(I,{color:g,weight:2,opacity:.7}).addTo(p).addTo(T);O[t]=e}$[t]=v,m[t]=T,M.push({postName:t,postDate:{text:D,dateObj:j},latlngs:I,markers:v})}const y=M.slice().sort((t,a)=>a.postDate.dateObj-t.postDate.dateObj);u&&(u.innerHTML="",y.forEach(t=>{const a=document.createElement("li");a.textContent=`${t.postName} — ${t.postDate.text}`,t.latlngs.length>0?a.onclick=()=>{Object.values(m).forEach(g=>n.removeLayer(g)),m[t.postName].addTo(n),n.fitBounds(L.latLngBounds(t.latlngs)),t.markers[0].openPopup(),c&&c.classList.remove("show")}:(a.classList.add("no-map"),a.onclick=()=>{k.open(`https://mattia-furlan.github.io/mont/escursioni/${t.postName}`,"_blank")}),u.appendChild(a)})),d.length>0&&n.fitBounds(L.latLngBounds(d))}function P(s={}){const o={...B,...s};if(n=null,c=document.getElementById(o.sidebarId),f=document.getElementById(o.toggleBtnId),u=document.getElementById(o.postListId),c||console.warn(`Sidebar with ID "${o.sidebarId}" not found`),f||console.warn(`Toggle button with ID "${o.toggleBtnId}" not found`),u||console.warn(`Post list with ID "${o.postListId}" not found`),S(),!z(o)){console.error("Failed to initialize map");return}const i=o.keywordsGeo||k.keywords_geo;if(!i||Object.keys(i).length===0){console.warn("No keywords_geo data provided");return}E(i),console.log("MattiaMapScriptModule initialized")}return{init:P,getMap:()=>n,getMasterLayerGroup:()=>p,getIndividualLayers:()=>m}})(window);window.MattiaMapScriptModule=MattiaMapScriptModule;
