(function(window){let imageBuffer=[];let currentBatchIndex=0;let slideshowContainer;let slideContainers=[];let shuffledImages=[];let activeSlide=0;let WindowBaseUrl;let initPhotos;let isRelive;const defaults={WindowBaseUrl:'',initPhotos:1,isRelive:false};function getCaptions(htmlDoc){const images=htmlDoc.getElementsByTagName('img');const captions=[];const captionElements=htmlDoc.getElementsByClassName('tr-caption');let captionIndex=0;for(let i=0;i<images.length;i++){let caption='';while(captionIndex<captionElements.length){const currentCaptionElement=captionElements[captionIndex];const nextImageElement=images[i+1];if(!nextImageElement||currentCaptionElement.compareDocumentPosition(nextImageElement)&Node.DOCUMENT_POSITION_FOLLOWING){caption=currentCaptionElement.textContent.trim();captionIndex++;break;}
break;}
captions.push(caption);}
return captions;}
function fetchData(){const feedUrl=isRelive?`${WindowBaseUrl}/data/all-relive-posts.json`:`${WindowBaseUrl}/data/all-posts.json`;fetch(feedUrl).then(response=>response.json()).then(data=>{const entries=data.feed.entry;entries.forEach(entry=>{const content=entry.content.$t;const parser=new DOMParser();const htmlDoc=parser.parseFromString(content,'text/html');const images=htmlDoc.getElementsByTagName('img');const postTitle=entry.title.$t;const captions=getCaptions(htmlDoc);for(let i=0;i<images.length;i++){const PhotosRange=localStorage.getItem('photosSliderValue')||initPhotos;let dataSkip=images[i].getAttribute('data-skip');if(dataSkip==="NA"||dataSkip===null||dataSkip===undefined){dataSkip="3";}
dataSkip=dataSkip.replace(/best/g,"0");dataSkip=dataSkip.replace(/cover/g,"-1");dataSkip=dataSkip.replace(/peak/g,"-2");const dataSkipValues=dataSkip.split(";");const isWithinRange=dataSkipValues.some(value=>{if(!isNaN(value)){const numericValue=parseFloat(value);return numericValue<=PhotosRange;}
return false;});if(isWithinRange){let imgSrc=images[i].getAttribute('src');imgSrc=imgSrc.replace(/\/s\d+\/|\/w\d+-h\d+\//,`/s400/`);const caption=captions[i]||'';imageBuffer.push({src:imgSrc,caption:caption,title:postTitle});}}});console.log('All entries fetched:',imageBuffer.length,'images');shuffleArray(imageBuffer);shuffledImages=imageBuffer.slice();buildSlides();}).catch(error=>console.error('Error fetching data:',error));}
function shuffleArray(array){for(let i=array.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[array[i],array[j]]=[array[j],array[i]];}}
function buildSlides(){slideshowContainer=document.querySelector('.slideshow-container');slideContainers=[document.querySelector('.slide1'),document.querySelector('.slide2')];adjustSlideshowHeight(slideContainers[0]);setTimeout(function(){showSlides();},500);}
function preloadImage(src){return new Promise((resolve,reject)=>{const img=new Image();function cleanup(){img.removeEventListener('load',onLoad);img.removeEventListener('error',onError);}
function onLoad(){cleanup();resolve(img);}
function onError(err){cleanup();reject(err||new Error(`Failed to load image: ${src}`));}
img.addEventListener('load',onLoad);img.addEventListener('error',onError);img.src=src;});}
async function showSlides(){if(currentBatchIndex>=shuffledImages.length){currentBatchIndex=0;}
const nextSlideIndex=(activeSlide+1)%2;const currentSlideContainer=slideContainers[activeSlide];const nextSlideContainer=slideContainers[nextSlideIndex];const entry=shuffledImages[currentBatchIndex];nextSlideContainer.querySelector('img').src=entry.src;nextSlideContainer.querySelector('.uppertext').textContent=entry.title;nextSlideContainer.querySelector('.text').textContent=entry.caption;const imgElement=nextSlideContainer.querySelector('img');imgElement.onerror=async function(){currentBatchIndex++;if(currentBatchIndex>=shuffledImages.length){currentBatchIndex=0;}
const nextEntry=shuffledImages[currentBatchIndex];imgElement.src=nextEntry.src;nextSlideContainer.querySelector('.uppertext').textContent=nextEntry.title;nextSlideContainer.querySelector('.text').textContent=nextEntry.caption;};if(currentBatchIndex+1<shuffledImages.length){const nextEntry=shuffledImages[currentBatchIndex+1];preloadImage(nextEntry.src);}
adjustSlideshowHeight(nextSlideContainer);currentSlideContainer.style.opacity=0;nextSlideContainer.style.opacity=1;setTimeout(()=>{activeSlide=nextSlideIndex;currentBatchIndex++;showSlides();},7000);}
function adjustSlideshowHeight(slideContainer){if(!slideshowContainer||!slideContainer)return;let image=slideContainer.querySelector('img');if(image.complete){let imageAspectRatio=image.naturalWidth/image.naturalHeight;let newHeight=slideshowContainer.offsetWidth/imageAspectRatio;slideshowContainer.style.height=`${newHeight}px`;}else{image.addEventListener('load',function(){adjustSlideshowHeight(slideContainer);});}}
function startRandomSlideshowOnInteraction(){window.removeEventListener('scroll',startRandomSlideshowOnInteraction);window.removeEventListener('mousemove',startRandomSlideshowOnInteraction);fetchData();}
function init(options={}){const settings={...defaults,...options};WindowBaseUrl=settings.WindowBaseUrl;initPhotos=settings.initPhotos;isRelive=settings.isRelive;window.addEventListener('scroll',startRandomSlideshowOnInteraction,{once:true});window.addEventListener('mousemove',startRandomSlideshowOnInteraction,{once:true});window.onresize=function(){adjustSlideshowHeight(slideContainers[activeSlide]);};}
window.MyRandomPhoto={init};})(window);